name: Publish crates (manual)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Revision or tag to release from. Leave empty to release from the workflow branch.'
        type: string
        required: false
        default: ''

jobs:

  publish-crates:
    runs-on: [ubuntu-24.04-github-hosted-32core]
    container:
      image: nvidia/cuda:12.5.0-devel-ubuntu20.04
    env:
      BELLMAN_CUDA_DIR: ${{ github.workspace }}/bellman-cuda
      CUDAARCHS: 89
    steps:

      - name: Prepare environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt update && apt install -y \
            pkg-config libclang-dev build-essential lldb lld \
            clang openssl libssl-dev gcc g++ wget curl jq
          echo "/usr/local/nvidia/bin:/usr/local/cuda/bin" >> $GITHUB_PATH

      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          ref: ${{ inputs.ref }}

      - name: Setup CMake
        run: |
          curl -LO https://github.com/Kitware/CMake/releases/download/v3.24.3/cmake-3.24.3-linux-x86_64.sh && \
            chmod +x cmake-3.24.3-linux-x86_64.sh && \
            ./cmake-3.24.3-linux-x86_64.sh --skip-license --prefix=/usr/local

      - name: Prepare bellman-cuda directory
        shell: bash
        # Curl ugliness is required because gh can't work with authentication: https://github.com/cli/cli/issues/2680.
        run: |
          release=($(curl --silent https://api.github.com/repos/matter-labs/era-bellman-cuda/releases | jq -r '.[0] | .name, .tarball_url, .assets[0].browser_download_url'))
          curl --silent -L "${release[1]}" --output bellman-cuda-source.tar.gz
          curl --silent -L "${release[2]}" --output bellman-cuda.tar.gz
          mkdir -p bellman-cuda
          tar xvfz bellman-cuda.tar.gz -C ./bellman-cuda
          tar xvfz bellman-cuda-source.tar.gz -C ./bellman-cuda --strip-components=1 --wildcards \*/src/

      - name: Publish crates
        uses: matter-labs/zksync-ci-common/.github/actions/publish-crates@v1
        with:
          skip_checkout: true
          gh_token: ${{ secrets.RELEASE_TOKEN }}
          cargo_registry_token: ${{ secrets.CRATES_IO_TOKEN }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK_RELEASES }}
